import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import BaseLayout from "../components/core/layouts/BaseLayout";
import { ExtendedNextPage } from "../types/next";

const Home: ExtendedNextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Emission Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full text-2xl font-medium mt-28 h-full flex justify-center items-center">
        Calculate carbon emission from your flights, commute and transport
      </main>
    </div>
  );
};

Home.Layout = BaseLayout;

export default Home;
